name: Repository Mirorring
on: [push, delete]
jobs:
  to-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2026/B-DOP-200-PAR-2-1-chocolatine-jeremy.elalouf.git
          ssh_private:
            ${{ secrets.SSH }}